// <SIMPLE_COLLECTIVE_SE_USB>
  #define  SIMPLE_COLLECTIVE_SE_PHYSICAL_THROTTLE_LATCH 0

  #define SIMPLE_COLLECTIVE_SE_USB_MIN 1023
  #define SIMPLE_COLLECTIVE_SE_USB_MAX 0

  #define SIMPLE_COLLECTIVE_SE_USB_THR_MIN 0
  #define SIMPLE_COLLECTIVE_SE_USB_THR_MAX 576

  #define SIMPLE_COLLECTIVE_SE_USB_IDLE_DETENT_AXIS_VAL 100 // throttle axis value at the detent mark
  #define SIMPLE_COLLECTIVE_SE_USB_IDLE_REL_BTN 8
  
  #define SIMPLE_COLLECTIVE_SE_USB_PHYSICAL_LATCH_MOD_JOY_BUTTON_1 5 // this button will be pressed on throttle cutoff, if IDLE REL button was pressed
  #define SIMPLE_COLLECTIVE_SE_USB_PHYSICAL_LATCH_MOD_JOY_BUTTON_2 6
  #define SIMPLE_COLLECTIVE_SE_USB_PHYSICAL_LATCH_MOD_JOY_BUTTON_3 7
    
// </SIMPLE_COLLECTIVE_SE_>
