// <SIMPLE_COLLECTIVE_SE_USB>

  //UNCOMMENT THE NEXT LINE TO SET UP CONFIGURATION VALUES
  //#define CALIBRATE_SIMPLE_COLL_SE_USB

  // ADJUST THESE VALUES FOR CALIBRATION
    #define COLL_EVO_USB_ENABLE_MAP_FUNCTION 1 // SET TO 0 TO SEE RAW VALUES
    #define COLL_EVO_USB_PHYS_Z_MIN 1
    #define COLL_EVO_USB_PHYS_Z_MAX 905
    #define COLL_EVO_USB_PHYS_THR0_MIN 782
    #define COLL_EVO_USB_PHYS_THR0_MAX 197
    #define COLL_EVO_USB_PHYS_THR0_MAX_MINUS_PHYS_THR0_MIN 585 // THR0 AXIS RANGE, LARGER NUMBER MINUS SMALLER NUMBER

  #define  SIMPLE_COLLECTIVE_SE_PHYSICAL_THROTTLE_LATCH 0

  #define SIMPLE_COLLECTIVE_SE_USB_MIN 1023
  #define SIMPLE_COLLECTIVE_SE_USB_MAX 0

  #define SIMPLE_COLLECTIVE_SE_USB_THR_MIN 0
  #define SIMPLE_COLLECTIVE_SE_USB_THR_MAX 585

  #define SIMPLE_COLLECTIVE_SE_USB_IDLE_DETENT_AXIS_VAL 100 // throttle axis value at the detent mark
  #define SIMPLE_COLLECTIVE_SE_USB_IDLE_REL_BTN 8
  
  #define SIMPLE_COLLECTIVE_SE_USB_PHYSICAL_LATCH_MOD_JOY_BUTTON_1 5 // this button will be pressed on throttle cutoff, if IDLE REL button was pressed
  #define SIMPLE_COLLECTIVE_SE_USB_PHYSICAL_LATCH_MOD_JOY_BUTTON_2 6
  #define SIMPLE_COLLECTIVE_SE_USB_PHYSICAL_LATCH_MOD_JOY_BUTTON_3 7
    
// </SIMPLE_COLLECTIVE_SE_>
