// <SINGLE_COLLECTIVE_EVO_USB>
#if (defined COLLECTIVE_STHR_EVO_USB)

  //UNCOMMENT THE NEXT LINE TO SET UP CONFIGURATION VALUES
  //#define CALIBRATE_SCOLL_EVO_USB

  // ADJUST THESE VALUES FOR CALIBRATION
    #define COLL_EVO_USB_ENABLE_MAP_FUNCTION 1 // SET TO 0 TO SEE RAW VALUES
    #define COLL_EVO_USB_PHYS_Z_MIN 0
    #define COLL_EVO_USB_PHYS_Z_MAX 1000
    #define COLL_EVO_USB_PHYS_THR0_MIN 149
    #define COLL_EVO_USB_PHYS_THR0_MAX 703
    #define COLL_EVO_USB_PHYS_THR0_MAX_MINUS_PHYS_THR0_MIN 559 //  PHYSICAL THR MAX MINUS THR MIN

  #define  SINGLE_COLLECTIVE_EVO_USB_PHYSICAL_THROTTLE_LATCH 1 // if your collective has a physical idle stop latch, set this to 1, otherwise set it to 0 for advanced throttle related functions to work

  #define SINGLE_COLLECTIVE_EVO_USB_MIN 1022
  #define SINGLE_COLLECTIVE_EVO_USB_MAX 19

  #define SINGLE_COLLECTIVE_EVO_USB_THR_MIN 0
  #define SINGLE_COLLECTIVE_EVO_USB_THR_MAX 559

  #define SINGLE_COLLECTIVE_EVO_USB_IDLE_DETENT_AXIS_VAL 183 // throttle axis value at the detent mark

  #define SINGLE_COLLECTIVE_EVO_USB_PHYSICAL_LATCH_MOD_JOY_BUTTON_1 5 // this button will be pressed on throttle cutoff, if IDLE REL button was pressed
  #define SINGLE_COLLECTIVE_EVO_USB_PHYSICAL_LATCH_MOD_JOY_BUTTON_2 6
  #define SINGLE_COLLECTIVE_EVO_USB_PHYSICAL_LATCH_MOD_JOY_BUTTON_3 7
  
#endif    
// </SINGLE_COLLECTIVE_EVO_USB>
